Feat 기본 UI 구현
eraser3031/CloneApp1_Calculator pull request #2
Opened 2022-05-29 12:45 UTC by eraser3031

## 작업내용
기본적인 계산기 UI 구현 ( Label, Button )

## 문제
- SwiftUI로 개발을 시작하다보니 UIKit에서 같은 사고방식으로 코드를 접근했을때 낯선 부분이 많았다.
이를테면 버튼을 만들 때 이니셜라이저에서 서브 뷰에 색상, 폰트 크기 같은 요소를 지정된 채로 불러오게 해서 코드를 깔끔하게 해두고 싶었는데 예로 UIButton의 폰트 텍스트 크기는 생성된 이후에 바꿔줘야 변경이 되는 이슈가 있어서 코드의 통일성을 깨야할 지 고민해야 하는 부분이 있었음. UIKit에 대한 지식이 부족하기 때문에 좀 더 공부해보고 이슈를 해결할 계획.

- 스토리보드 없이 개발해보는 첫 시도인데 많은 버튼 요소를 어떻게 적절하게 생성하고 관리할 지 좀 더 생각해볼 필요가 있을 것 같다. 더군다나 공학용 계산 버튼도 추가된다면 열댓줄의 코드를 버튼을 생성하는 것만으로 차지하는 것이 좋은 코드같지 않아보임

## 다음으로 구현해야 할 것
세로모드 시 공학용 계산기 변환 ( 버튼 추가 및 AutoLayout 지정)
버튼 기능 및 애니메이션 (isHighlighted, 연산 버튼, AC -> C) 구현

2022-05-29 17:41 UTC, JaewoongLee-swift commented on CloneApp1_Calculator/CalculatorButton.swift
> +    case scientific
가로모드때 공학용계산버튼을 위한 case인가요?

2022-05-29 18:59 UTC, JaewoongLee-swift requested changes
점검해보면 좋을 부분과 PR에서 고민하신 부분에 대한 코멘트를 남겼습니다. 도움이 되셨으면 좋겠습니다.
PR 올리시면 디엠주세요!! 최대한 빨리 리뷰 남기겠습니다.

2022-05-29 18:59 UTC, JaewoongLee-swift commented on CloneApp1_Calculator/CalculatorViewController.swift
>      override func viewDidLoad() {
UI선언 코드가 viewDidLoad() 밖에 있는게 가독성과 이후 view의 생명주기를 이해하고 사용하는데 도움이 될 것 같습니다.
(view의 생명주기 참고 : https://zeddios.tistory.com/43)
저는 viewDidLoad() 내부엔 레이아웃, NavigationBar 설정과 같은 메소드를 따로 해당 뷰의 extension으로 빼놓고 선언해 사용하는 편입니다.

2022-05-29 18:59 UTC, JaewoongLee-swift commented on CloneApp1_Calculator/CalculatorViewController.swift
> +        let stacks = [firstStack, secondStack, thirdStack, fourthStack, fifthStack]
stackView 선언과 각각의 addSubview, autolayout 설정은 위의 viewDidLoad() 관련 코멘트와 동일하게 extension으로 따로 빼서 선언하면 가독성에 도움이 될 것 같습니다.
추가로 변수명을 stack에서 stackView로 하는건 어떨까 이야기를 나눠보고 싶습니다!

(ex)
extension CalculatorViewController {
// 각종 스택뷰 선언
   let firstStack = UIStackView....

   func setupLayout() {
// UI요소 오토레이아웃 설정 
   }

   func setStack() {
// stakc설정
   }

}

2022-05-29 18:59 UTC, JaewoongLee-swift commented on CloneApp1_Calculator/CalculatorViewController.swift
> +        for stack in stacks {
고차함수 forEach와 for문 비교를 하면서 어떤게 더 좋을지 영과 함께 이야기 나누면 좋을것 같습니다.
(저도 어떤게 더 나은지 아직 잘 모르겠어요)

2022-05-30 11:02 UTC, eraser3031 commented on CloneApp1_Calculator/CalculatorButton.swift
> +    case scientific
네 맞아요. scientific이 가로모드를 위한 케이스입니다!

2022-05-30 11:40 UTC, merged